= About Ktirio Urban Building Benchmarks

== Introduction

This catalog provides a collection of benchmarks for urban building energy simulation models. 
The benchmarks are designed to evaluate the performance of simulation models in predicting the energy consumption of urban buildings. 
The benchmarks are based on real-world data and are intended to be used by researchers, developers, and practitioners to assess the accuracy and reliability of their simulation models.

== Build the site

Here is the procedure to build the site:

[source,shell]
----
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install feelpp-benchmarking
npm i
npm run antora
npm run start
----

== Acknowledgments

Funded by the European Union. This work has received funding from the European High-Performance Computing Joint Undertaking (EuroHPC JU) and Poland, Germany, Spain, Hungary, France, and Greece under grant agreement number 101093457. This publication expresses the opinions of the authors and not necessarily those of the EuroHPC JU and Associated Countries which are not responsible for any use of the information contained in this publication.

Part of this work was also funded by:

- The France 2030 NumPEx Exa-MA (ANR-22-EXNU-0002) project managed by the French National Research Agency (ANR)
- AMIES, the French agency for interaction between mathematics and enterprises
- CNRS through its prematuration programme.

We acknowledge the EuroHPC Joint Undertaking for awarding this project access through EuroHPC Development Access grants EHPC-DEV-2024D05-025 and EHPC-DEV-2023D08-047 to the EuroHPC JU supercomputers:

- Kumi, hosted by CSC (Finland) and the Lumi consortium
- MeluXina hosted by LuxProvide, Luxembourg
- Karolina hosted by IT4Innovations National Supercomputing Center, Czechia
- Discoverer hosted by Sofia Tech Park, Bulgaria
- Vega hosted by IZUM, Slovenia
- Leonardo hosted by CINECA, Italy.

Finally, the authors would like to acknowledge the many fruitful discussions with our partners Luc Kern from Synapse Concept and Leopold Fischer from Cisco Meraki, our colleagues:

- From Hidalgo2 ICCS: Kostis Nikas, Aristomenis Theodoridis, and Petros Anastasiadis for the discussions on Reframe and joining their EuroHPC access grant
- Hidalgo2 HLRS: Sameer Haroon for the discussions on CI/CD
- Pierre Alliez from INRIA Titane and Andreas Fabri from Geometry Factory regarding the discussions on CGAL and using Polygon Repair
- Our former colleague Zohra Djatouti, now at Kipsum, with whom we initiated this endeavor.
