site:
  title: Ktirio Benchmarks
  start_page: ktirio_benchmarks::index.adoc
  url: https://feelpp.github.io/bench.ktirio.fr/
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
asciidoc:
  extensions:
  - '@feelpp/asciidoctor-extensions'